# -Wextra-semi: GCC < 10 does not have this.
# -Wunreachable-code: GCC no longer has this option.

name: Linux GCC

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-linux-gcc
  cancel-in-progress: true

jobs:
  # Build libamrex and all tests
  tests-nofortran:
    name: GNU@12 C++17 w/o Fortran [tests]
    runs-on: ubuntu-22.04
    #
    # /home/runner/work/amrex/amrex/Src/Base/AMReX_IntVect.H:194:92: error: array subscript -1 is below array bounds of ‘int [3]’ [-Werror=array-bounds]
    # int& operator[] (int i) noexcept { BL_ASSERT(i>=0 && i < AMREX_SPACEDIM); return vect[i]; }
    #
    # inlined from ‘const amrex::MultiFab& amrex::EBFArrayBoxFactory::getVolFrac() const’ at /home/runner/work/amrex/amrex/Src/EB/AMReX_EBFabFactory.H:53:91,
    # /usr/include/c++/12/bits/shared_ptr_base.h:1666:16: error: potential null pointer dereference [-Werror=null-dereference]
    #
    env: {CXXFLAGS: "-fno-operator-names -Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual -Wunreachable-code -Wnon-virtual-dtor -Wlogical-op -Wmisleading-indentation -Wduplicated-cond -Wduplicated-branches -Wmissing-include-dirs -Wno-array-bounds -Wno-null-dereference"}
    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: |
        .github/workflows/dependencies/dependencies_gcc.sh 12
        .github/workflows/dependencies/dependencies_clang-tidy.sh 14
    - name: Build & Install
      run: |
        mkdir build
        cd build
        cmake ..                        \
            -DCMAKE_BUILD_TYPE=RelWithDebINfo \
            -DCMAKE_VERBOSE_MAKEFILE=ON \
            -DAMReX_ASSERTIONS=ON       \
            -DAMReX_TESTING=ON          \
            -DAMReX_BOUND_CHECK=ON      \
            -DAMReX_FPE=ON              \
            -DAMReX_EB=ON               \
            -DAMReX_ENABLE_TESTS=ON     \
            -DAMReX_FORTRAN=OFF         \
            -DAMReX_PARTICLES=ON        \
            -DAMReX_FORTRAN=OFF         \
            -DCMAKE_C_COMPILER=$(which gcc-12)     \
            -DCMAKE_CXX_COMPILER=$(which g++-12)   \
            -DCMAKE_CXX_STANDARD=17     \
            -DAMReX_CLANG_TIDY=ON       \
            -DAMReX_CLANG_TIDY_WERROR=ON
        make -j 2


