name: hip

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-hip
  cancel-in-progress: true

jobs:
  hip-debug-link:
    name: HIP DEBUG Link Error
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: |
        .github/workflows/dependencies/dependencies_hip.sh
    - name: Build
      run: |
        cd Tests/Amr/Advection_AmrCore/Exec
        make -j2 AMD_ARCH=gfx90a USE_HIP=TRUE USE_MPI=FALSE DEBUG=TRUE
