name: PostPR
on:
  pull_request:
    types:
      - closed

# Because this workflow is run in the context of a pull_request event, it
# does not have the permission to remove caches. We use this workflow to
# trigger CleanUpCachePostPR to remove caches.

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "This workflow will trigger CleanUpCachePostPR."
