
PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

DIM        = 2
#DIM       = 3

COMP	   = gnu

USE_MPI    = FALSE
USE_OMP    = FALSE 
USE_CUDA   = TRUE

Bpack   := ./Make.package 
Blocs   := . 

include Make.Adv
